#include "ac_boxTrick01.h"

#include "m_name_table.h"

#ifdef TARGET_PC
static void BoxTrick01_Actor_ct(ACTOR* actor, GAME* game);
static void BoxTrick01_Actor_dt(ACTOR* actor, GAME* game);
static void BoxTrick01_Actor_move(ACTOR* actor, GAME* game);
#else
extern void BoxTrick01_Actor_ct(ACTOR* actor, GAME* game);
extern void BoxTrick01_Actor_dt(ACTOR* actor, GAME* game);
extern void BoxTrick01_Actor_move(ACTOR* actor, GAME* game);
#endif


#ifdef TARGET_PC
/* Typed stubs for (TYPE)&none_proc1 casts — wasm call_indirect requires
 * exact signature match. Generated by fix_none_proc1_casts.py. */
static void _none_mActor_proc(ACTOR* _p0, GAME* _p1) { (void)_p0; (void)_p1; }
#endif

ACTOR_PROFILE BoxTrick01_Profile = {
    mAc_PROFILE_BOXTRICK01,
    ACTOR_PART_BG,
    ACTOR_STATE_NO_MOVE_WHILE_CULLED | ACTOR_STATE_NO_DRAW_WHILE_CULLED,
    ETC_BOXTRICK,
    ACTOR_OBJ_BANK_KEEP,
    sizeof(BOXTRICK01_ACTOR),
    &BoxTrick01_Actor_ct,
    &BoxTrick01_Actor_dt,
    &BoxTrick01_Actor_move,
    _none_mActor_proc,
    NULL
};


static void BoxTrick01_Actor_ct(ACTOR* actor, GAME* game){

}

static void BoxTrick01_Actor_dt(ACTOR* actor, GAME* game){

}

static void BoxTrick01_Actor_move(ACTOR* actor, GAME* game){

}