apply plugin: 'com.android.application'

android {
    namespace 'com.acpc.port'
    compileSdk 37

    defaultConfig {
        applicationId "com.acpc.port"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "0.1.0"

        ndk {
            abiFilters "armeabi-v7a"
        }

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared",
                          "-DANDROID_ARM_NEON=TRUE"
            }
        }
    }

    buildTypes {
        debug {
            debuggable true
            jniDebuggable true
        }
        release {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            path "../../CMakeLists.txt"
            version "3.22.1+"
        }
    }

    sourceSets {
        main {
            java.srcDirs = [
                'src/main/java',
                '../../lib/SDL2-src/android-project/app/src/main/java'
            ]
            assets.srcDirs = ['src/main/assets']
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.18.0'
}
